import 'Product.dart';

G g=G();
 Map<String, String> en = {
  "intro_qus": "What Is Green Building ?",
  "body_intro":"They are buildings that are designed to achieve sustainability based on some international standards from specialized institutions that measure the extent to which the building is compatible with the environment.It is an environmentally responsible method that supports resource efficiency.",
  "next":"next",
  "btnNext":"Next",
  "showRisks":"Show Risks",
  "Kind Of Building":"Kind Of Building",
  "Change Language":"Change Language",
  "Exit":"Exit",
  "Contact_Us":"Contact Us",
  "Solutions":"Solutions",
  //home screan
  "Email":"Email",
  "area":"(m²) area",
  "Name":"Name",
  "Time":"Time",
  "Project Time":"Project Time",
  "Cost":"Cost(\$)",
  "Project Cost/Total Area":"Project Cost/Total Area",
  "should fill any field":"should fill any field",

  //suggestion
  "Suggestions":"Suggestions",
  "Risk mitigation":"Risk mitigation measure",
   "${g.Suggestion[0]}":"Emergency contingency funds",
  "${g.Suggestion[1]}":"Use previous green projects as a reference",
  "${g.Suggestion[2]}":"Investing in the search for green building materials and processes",
  "${g.Suggestion[3]}":"Develop promotional programs for team members",
  "${g.Suggestion[4]}":"Effective management system for design changes",
  "${g.Suggestion[5]}":"Improving communication and coordination among stakeholders",
  "${g.Suggestion[6]}":"Understand customer's goal in green building project",
  "${g.Suggestion[7]}":"Quality control of construction drawings and specifications",
  "${g.Suggestion[8]}":"Take advantage of the integrated design process",
  "${g.Suggestion[9]}":"Buy insurance when allocating risks",
  "${g.Suggestion[10]}":"Advertisements and programs to increase community awareness of the importance of green facilities",
  "${g.Suggestion[11]}":"Tempting the use of green buildings",
  "${g.Suggestion[12]}":"Incentives and financial measures from the government",
  //
  "Risks Of Green Building":"Risks Of Green Building",
  "Risks Of Traditional Building":"Risks Of Traditional Building",
  //title
  "cost":"Cost\$",
  "time":"time M",
  "rate":" % Si",
  " Kind of Danger":" Kind of Danger",
  "Green Building":"Green Building",
  "Traditional Building":"Traditional Building",
// risks
  "financial risk":"financial risk",
  "Delay in schedule risk":"Delay in schedule risk",
  "Building products and materials ":"Building products and materials ",
  "Design guideline availability ":"Design guideline availability ",
  "Energy saving uncertainty ":"Energy saving uncertainty ",
  "green building certification results ":"green building certification results ",
  "traditional building certification results ":"traditional building certification results ",
  "Team performance risk":"Team performance risk",
  "client is goal uncertainty ":"client is goal uncertainty ",
  "regulatory / legislative risk":"regulatory / legislative risk",
  "Design risk ":"Design risk ",
  "Lack of communications":"Lack of communications",
  "incomplete drawings & spaces":"incomplete drawings & spaces",
  "lack of contract":"lack of contract",
  "fluctuation in exchange rates ":"fluctuation in exchange rates ",
  "complex procedures to obtain approvals ":"complex procedures to obtain approvals ",
  "import / export restrictions ":"import / export restrictions ",
  "unclear allocation of roles and responsibilities ":"unclear allocation of roles and responsibilities ",
  "shortage of funds ":"shortage of funds ",
  "unclear requirements of owners ":"unclear requirements of owners ",
  "inappropriate interventions of clients":"inappropriate interventions of clients",
  "loose control over subcontractors ":"loose control over subcontractors ",
  "unclear design details and specifications ":"unclear design details and specifications ",
  "poor communication among projects stakeholders":"poor communication among projects stakeholders",
  "lack of qualified professionals with proper design expertise":"lack of qualified professionals with proper design expertise",
  "technical issues":"technical issues",
  "unfamiliarity with green materials and construction technologies ":"unfamiliarity with green materials and construction technologies ",
  "lack of experience":"lack of experience",
  "setting expectations too high ":"setting expectations too high ",
  "unskilled workers ":"unskilled workers ",
  "poor design ":"poor design ",
  "unfamiliarity with construction process":"unfamiliarity with construction process",
  "fluctuations in labor / material rates ":"fluctuations in labor / material rates ",
  "high target for  green mark ratting ":"high target for  green mark ratting ",
  "high target for  traditional mark ratting ":"high target for  traditional mark ratting ",
  "unfamiliarity with traditional  materials and construction technologies ":"unfamiliarity with traditional  materials and construction technologies ",
  "print":"Print Result",
  "printMain":"Print File"

};
 Map<String, String> ar = {
  "intro_qus": "ما هي الأبنية الخضراء ؟  ",
  "body_intro":"\ هي مبانى يتم تصميمها لتحقيق الاستدامة' وذلك استنادا إلي بعض المعايير الدولية من المؤسسات المختصة التي تقيس مدي توافق المبني مع البيئة.وهي طريقة مسئولة بيئياً وتدعم كفاءة الموارد",
  "next":"التالي",
  "btnNext":"معرفة المزيد",
  "showRisks":"عرض المخاطر",
  "Kind Of Building":"نوع المبني",
  "Change Language":"تغير اللغة",
  "Exit":"الخروج من البرنامج",
  "Contact_Us":"تواصل معنا ",
  "Solutions":"مقترحات الحل ",
  "Email":"البريد الإلكتروني",
  "area":"مساحة المبنى (م²)",
  "Name":"الإسم",
  "Time":"وقت المشروع",
  "Project Time":"الوقت المحدد للمشروع",
  "Cost":"تكلفة المبنى (\$)",
  "Project Cost/Total Area":"التكلفة التقديرية/اجمالى المساحة",
  "should fill any field":"يجب ملئ اي حقل",

  // المقترحات
  "Suggestions":"مقترحات الحل",
  "Risk mitigation":"قياس تخفيف المخاطر",
   "${g.Suggestion[0]}":"صناديق الطوارئ في حالات الطوارئ",
  "${g.Suggestion[1]}":"استخدم المشاريع الخضراء السابقة كمرجع",
  "${g.Suggestion[2]}":"الاستثمار في البحث عن مواد وعمليات البناء الأخضر",
  "${g.Suggestion[3]}":"تطوير برامج ترويجية لأعضاء الفريق",
  "${g.Suggestion[4]}":"نظام إدارة فعال لتغيرات التصميم",
  "${g.Suggestion[5]}":"تحسين الاتصال والتنسيق بين أصحاب المصلحة",
  "${g.Suggestion[6]}":"فهم هدف العملاء في مشروع المباني الخضراء",
  "${g.Suggestion[7]}":"مراقبة جودة الرسومات والمواصفات الإنشائية",
  "${g.Suggestion[8]}":"استفد من عملية التصميم المتكاملة",
  "${g.Suggestion[9]}":"شراء التأمين عند تخصيص المخاطر",
  "${g.Suggestion[10]}":"إعلانات وبرامج لزيادة وعي المجتمع بأهمية المرافق الخضراء",
  "${g.Suggestion[11]}":"إغراء استخدام المباني الخضراء",
  "${g.Suggestion[12]}":"الحوافز والتدابير المالية من الحكومة",
  //app par
  "Risks Of Green Building":"مخاطر المشاريع الخضراء",
  "Risks Of Traditional Building":"مخاطر المباني التقليدية",
  // risks title
  "cost":"التكلفة \$",
  "time":"M الوقت",
  "rate":" % Si",
  " Kind of Danger":"   نوع الخطر   ",
  "Green Building":"المباني الخضراء",
  "Traditional Building":"المباني التقليدية",

// risks solution
  "financial risk":"مخاطر مالية",
  "Delay in schedule risk":"التأخير في جدول المخاطر",
  "Building products and materials ":"منتجات ومواد البناء",
  "Design guideline availability ":"توافر الدليل الإرشادي للتصميم",
  "Energy saving uncertainty ":"عدم اليقين بشأن توفير الطاقة",
  "green building certification results ":"نتائج شهادة المباني الخضراء",
  "traditional building certification results ":"نتائج شهادة المباني الخضراء",
  "Team performance risk":"مخاطر أداء الفريق",
  "client is goal uncertainty ":"العميل هو هدف عدم اليقين",
  "regulatory / legislative risk":"المخاطر التنظيمية / التشريعية",
  "Design risk ":"مخاطر التصميم",
  "Lack of communications":"قلة الاتصالات",
  "incomplete drawings & spaces":"رسومات ومساحات غير مكتملة",
  "lack of contract":"عدم وجود عقد",
  "fluctuation in exchange rates ":"تقلب في أسعار الصرف",
  "complex procedures to obtain approvals ":"إجراءات معقدة للحصول على الموافقات",
  "import / export restrictions ":"قيود الاستيراد / التصدير",
  "unclear allocation of roles and responsibilities ":"التوزيع غير الواضح للأدوار والمسؤوليات",
  "shortage of funds ":"نقص الأموال",
  "unclear requirements of owners ":"متطلبات غير واضحة للمالكين",
  "inappropriate interventions of clients":"التدخلات غير الملائمة للعملاء",
  "loose control over subcontractors ":"سيطرة فضفاضة على المقاولين من الباطن",
  "unclear design details and specifications ":"تفاصيل و تصاميم غير واضحة",
  "poor communication among projects stakeholders":"ضعف التواصل بين أصحاب المصلحة في المشاريع",
  "lack of qualified professionals with proper design expertise":"نقص المهنيين المؤهلين ذوي الخبرة المناسبة للتصميم",
  "technical issues":"مشكلة تقنية",
  "unfamiliarity with green materials and construction technologies ":"عدم الإلمام بالمواد الخضراء وتقنيات البناء",
  "lack of experience":"نقص الخبرة",
  "setting expectations too high ":"وضع توقعات عالية للغاية",
  "unskilled workers ":"العمال غير المهرة",
  "poor design ":"تصميم رديء",
  "unfamiliarity with construction process":"عدم الإلمام بعملية البناء",
  "fluctuations in labor / material rates ":"تقلبات في معدلات العمالة / المواد",
  "high target for  green mark ratting ":"هدف مرتفع للعلامة الخضراء",
  "high target for  traditional mark ratting ":"هدف مرتفع للعلامة التقليدية",
  "unfamiliarity with traditional  materials and construction technologies ":"عدم الإلمام بالمواد التقليدية وتقنيات البناء",
  "print":"طباعة النتائج",
  "printMain":"طباعة الملف"

};
