const phone = "+2001032220065";
const whatsappUrl = "whatsapp://send?phone=$phone";

class G {
  List<double> green = [
    .79,
    .80,
    .79,
    .79,
    .80,
    .80,
    .79,
    .79,
    .79,
    .79,
    .78,
    .78,
    .78,
    .77,
    .78,
    .79,
    .77,
    .78,
    .79,
    .79,
    .79,
    .78,
    .78,
    .78,
    .77,
    .78,
    .76,
    .78,
    .76,
    .78,
    .78,
    .78,
    .78
  ];
  List<String> greenRatio = [
    '79 %',
    '80 %',
    '79 %',
    '79 %',
    '80 %',
    '80 %',
    '79 %',
    '79 %',
    '79 %',
    '79 %',
    '78 %',
    '78 %',
    '78 %',
    '77 %',
    '78 %',
    '79 %',
    '77 %',
    '78 %',
    '79 %',
    '79 %',
    '79 %',
    '78 %',
    '78 %',
    '78 %',
    '77 %',
    '78 %',
    '76 %',
    '78 %',
    '76 %',
    '78 %',
    '78 %',
    '78 %',
    '78 %',
  ];
  List<String> greenNames = [
    "financial risk",
    "Delay in schedule risk",
    "Building products and materials",
    "Design guideline availability",
    "Energy saving uncertainty",
    "green building certification results",
    "traditional building certification results",
    "Team performance risk",
    "client is goal uncertainty",
    "regulatory / legislative risk",
    "Design risk",
    "Lack of communications",
    "incomplete drawings & spaces",
    "lack of contract",
    "fluctuation in exchange rates",
    "complex procedures to obtain approvals",
    "import / export restrictions",
    "unclear allocation of roles",
    "shortage of funds",
    "unclear requirements of owners",
    "inappropriate interventions of clients",
    "loose control over subcontractors ",
    "unclear design",
    "poor communication",
    "lack of qualified professionals",
    "technical issues",
    "unfamiliarity with materials",
    "lack of experience",
    "expectations too high",
    "unskilled workers",
    "poor design",
    "unfamiliarity with construction process",
    "fluctuations in material rates ",
    "high target for mark ratting",
  ];
  List <String> Suggestion =[
    "emergency contingency funds",
    "Use previous green projects as a reference",
    "Investing in the search for green building materials and processes",
    "Develop promotional programs for team members",
    "Effective management system for design changes",
    "Improving communication and coordination among stakeholders",
    "Understand customer's goal in green building project",
    "Quality control of construction drawings and specifications",
    "Take advantage of the integrated design process",
    "Buy insurance when allocating risks",
    "Advertisements and programs to increase community awareness of the importance of green facilities",
    "Tempting the use of green buildings",
    "Incentives and financial measures from the government",
  ];
  List<double> trad = [
    .71,
    .75,
    .79,
    .76,
    .76,
    .77,
    .77,
    .77,
    .78,
    .79,
    .77,
    .77,
    .75,
    .78,
    .74,
    .77,
    .72,
    .75,
    .75,
    .74,
    .75,
    .78,
    .76,
    .76,
    .73,
    .78,
    .77,
    .77,
    .79,
    .77,
    .76,
    .78,
    .78
  ];
  List<String> tradRatio = [
    '71 %',
    '75 %',
    '79 %',
    '76 %',
    '76 %',
    '77 %',
    '77 %',
    '77 %',
    '78 %',
    '79 %',
    '77 %',
    '77 %',
    '75 %',
    '78 %',
    '74 %',
    '77 %',
    '72 %',
    '75 %',
    '75 %',
    '74 %',
    '75 %',
    '78 %',
    '76 %',
    '76 %',
    '73 %',
    '78 %',
    '77 %',
    '77 %',
    '79 %',
    '77 %',
    '76 %',
    '78 %',
    '78 %',
  ];
}
